name: Actions Workflow

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs: 
  setup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with: 
          version: latest
          platform: x84
      - name: Configure
        run: ./configure
      - name: Make 
        run: make
      - name: Echo "Hello world"
        run: ./lessecho "Hello world"
      - name: zip
        run: zip --version
      - name: zipping
        run: | 
          zip Test.zip charset.c  
          find -name Test.zip



