name: Actions Workflow

on:
  push:

env: 
  SSH_KEY: ${{secrets.SSHKEY}}

jobs: 
  setup-build:
    runs-on: 
      - self-hosted
      - label-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with: 
          version: latest
          platform: x84
      - name: Configure
        run: ./configure
      - name: Make 
        run: make
      - name: Echo "Hello world"
        run: ./lessecho "Hello world"
      - name: zip
        run: zip --version
      - name: Remote SSH 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
      - name: zipping
        run: | 
          tar -czf Test.tar.gz charset.c
          
          


