name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up GCC
        uses: egor-tensin/setup-gcc@v1
        with: 
          version: latest
          platform: x84