name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: Run image
        run: |
          sh configure
      - name: Checkout
        uses: actions/checkout@v2