name: Actions Workflow

on:
  schedule:
    - cron: '0 10 * * *'
    - cron: '3 10 * * *'
    - cron: '6 10 * * *'

jobs: 
  setup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with: 
          version: latest
          platform: x84
      - name: Configure
        run: ./configure
      - name: Make 
        run: make
      - name: Echo "Hello world"
        run: ./lessecho "Hello world"

